---
name: "MediaSegments API"
guid: "6f0aaab5-e251-4a6d-b8d5-bc8c65222051"
version: "1.0.3.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Create and delete Media Segments"
description: >
  Provide an extended HTTP API to create and delete MediaSegments
category: "General"
owner: "intro-skipper"
artifacts:
- "Jellyfin.Plugin.MediaSegmentsApi.dll"
changelog: >
  changelog
